services:
  - type: web
    name: valorant-overlay
    env: node
    buildCommand: npm run build
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: / 